### ISSUE TITLE
Adding Rust (.rs) file to support Leptos.

### ISSUE THREAD

**Issue by kuskhan** [dejmedus/tailwind-sorter#13]
First of all, thank you for creating this wonderful extension.
I would like to suggest adding Rust file extension support to enable compatibility with [Leptos](https://leptos.dev/).
I've tested this by adding the following line, and can confirm it works well with `.rs` files in the Leptos framework:
```typescript
// tailwind-sorter/src/extension.ts

...
    const languages = [
      "html",
      "vue",
      "javascriptreact",
      "typescriptreact",
      "elixir",
      "phoenix-heex",
      "astro",
      "rust",  // here added
    ];
...
```

an example sorted by the extension:
```rust
// my-project/src/app.rs

/// Renders the home page of your application.
#[component]
fn HomePage() -> impl IntoView {
    // Creates a reactive value to update the button
    let count = RwSignal::new(0);
    let on_click = move |_| *count.write() += 1;

    view! {
        <h1 class="flex flex-row">"Welcome to Leptos!"</h1>
        <button on:click=on_click>"Click Me: " {count}</button>
    }
}
```

**Comment by dejmedus** [comment]
Thank you for the link/examples and testing this out! Leptos looks cool

Should now work on `.rs` files in v0.0.83 [#14]

**Comment by kuskhan** [comment]
Thank you so much for the quick implementation of Leptos (Rust) support.
When I opened VS Code this morning, the extension was updated and it's working perfectly.
