### ISSUE TITLE
@apply not supported

### ISSUE THREAD

**Issue by robertorinaldi-dev** [dejmedus/tailwind-sorter#16]
The plugin doesn't seem to work with @apply classes and there doesn't seem to be any possible configuration to enable it.

Are there any plans to add support for it?

Thank you

**Comment by dejmedus** [comment]
`@apply` rules should now be sorted within any [supported file](https://github.com/dejmedus/tailwind-sorter?tab=readme-ov-file#language-support) in v0.0.90 :) #17
