### ISSUE TITLE
Possible to add support for Phoenix LiveView templates?

### ISSUE THREAD

**Issue by weelink** [dejmedus/tailwind-sorter#4]
Tailwind is commonly used in [Phoenix](https://github.com/phoenixframework/phoenix) and [Phoenix LiveView](https://github.com/phoenixframework/phoenix_live_view).

There are 2 ways to render HTML. Either a separate template file (extension `.html.heex` with language id `phoenix-heex`) or in an Elixir module (extension `.ex` and language id `elixir`).

Is it possible to include these language identifiers?

When I change the language to HTML for any of these types of files, then this extension seems to work perfectly already.

**Comment by dejmedus** [comment]
Thank you for the explanation/links/language ids! Should now work in any vscode workspace that recognizes the elixir/phoenix-heex languages #5

**Comment by weelink** [comment]
I've updated the extension and it works perfectly.
Thank you!
