### ISSUE TITLE
Is it possible to sort at variable not just className

### ISSUE THREAD

**Issue by zoom2009** [dejmedus/tailwind-sorter#7]
here my code I was use tailwindmerge to define classes look like this

```typescript
const classes = {
  container: tw(`flex flex-col items-stretch lg:text-red-500 mt-4 text-[20px]`),
  col1: tw(`w-[55.56%] flex flex-col`),
  col2: tw(`flex flex-1`),
}
```

but it not work, It work only `className` at html element
How can I make your `tailwind-sorter` with variable

thank you.

**Comment by dejmedus** [comment]
I added a custom prefixes array to help with this [#8]. You'll need to:

- Update to version 0.0.8
- Search for `Tailwind Sorter: Custom Prefixes` in settings
- Add tw(

Should work okay, but please let me know if there are any issues

**Comment by zoom2009** [comment]
It's work, thank for fast response :D
